main/default/objects/Quality_Site_Assessment__c/Quality_Site_Assessment__c.object-meta.xml
<CustomObject>
    <label>Quality Site Assessment</label>
    <nameField>
        <label>Quality Site Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quality Site Assessment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Quality_Site_Assessment_Note__c/Quality_Site_Assessment_Note__c.object-meta.xml
<CustomObject>
    <label>Quality Site Assessment Note</label>
    <nameField>
        <label>Quality Site Assessment Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Site Assessment Note</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Quality_Site_Assessment_Note__c/fields/QSA_Name__c.field-meta.xml
<CustomField>
    <fullName>QSA_Name__c</fullName>
    <label>QSA Name</label>
    <referenceTo>Quality_Site_Assessment__c</referenceTo>
    <relationshipLabel>Quality Site Assessment Note</relationshipLabel>
    <relationshipName>Quality_Site_Assessment_Note</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/ImageCaptureClass_TestClass.cls
@isTest
public class ImageCaptureClass_TestClass {
    
    @isTest
    public static void testing(){
        Quality_Site_Assessment__c qsaInstance = new Quality_Site_Assessment__c();
        qsaInstance.Name='Qsa';
        insert qsaInstance;
        
        Quality_Site_Assessment_Note__c qsa=new Quality_Site_Assessment_Note__c();
        qsa.QSA_Name__c =qsaInstance.id;
        insert qsa;
        
        ApexPages.StandardController ImageCapture = new ApexPages.StandardController(qsa);
        ImageCaptureClass captureClass=new ImageCaptureClass(ImageCapture);
                
        List<String> noteList=new List<String>();
        List<String> imageList=new List<String>();
        
        for(Integer i=0;i<5;i++){
            String hello=' '+ i;
            imageList.add(hello);
            noteList.add(hello);
        }
        String hello='';
        ImageCaptureClass.getStoreImage(imageList,noteList,hello);
        
        ImageCaptureClass.getImagesList(qsaInstance.Id);
        
            }
}