main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Receivables__c/Receivables__c.object-meta.xml
<CustomObject>
    <label>Receivables</label>
    <nameField>
        <label>Object Receivables Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Receivables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Receivables__c/fields/Financial_Account__c.field-meta.xml
<CustomField>
    <fullName>Financial_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Account</label>
    <referenceTo>Financial_Account__c</referenceTo>
    <relationshipLabel>Receivables</relationshipLabel>
    <relationshipName>Receivables</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/SumTotalAmount_TestClass.cls
@isTest
public class SumTotalAmount_TestClass {

    @isTest
    public static void sumTest(){
        Financial_Account__c fa=new Financial_Account__c();
        fa.Name='finance';
        insert fa;
        
        Receivables__c rc=new Receivables__c();
        rc.Name='recievables';
        rc.Financial_Account__c=fa.Id;
        rc.Total_Amount__c=23000;
        insert rc;
        
        SumTotalAmount.sumAmount();
    }
}