main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Property__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Property__c/fields/Last_Sale_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Sale_Date__c</fullName>
    <label>Last Sale Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Property__c/fields/Last_Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Last_Sale_Price__c</fullName>
    <label>Last Sale Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

main/default/classes/UpdateContactAcquisition_TestClass.cls
@isTest
public class UpdateContactAcquisition_TestClass {

    @isTest
    public static void updateContact(){
        
        Contact c=new Contact();
        c.LastName='con';
        insert c;
        
        Property__c prop=new Property__c();
        prop.Last_Sale_Date__c=System.today();
        prop.Last_Sale_Price__c=1000;
        prop.Contact__c=c.id;
        prop.Name='property';
        insert prop;
        
    }
}