main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Plan__c/fields/Travel_Hours__c.field-meta.xml
<CustomField>
    <fullName>Travel_Hours__c</fullName>
    <label>Travel Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Plan__c/fields/Travel_Location__c.field-meta.xml
<CustomField>
    <fullName>Travel_Location__c</fullName>
    <label>Travel Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/PlanTravelHours_TestClass.cls
@isTest
public class PlanTravelHours_TestClass {

    @isTest
    public static void testTotalHours(){
        Plan__c plan=new Plan__c();
        plan.Travel_Hours__c=50;
        plan.Travel_Location__c='A;B;F';
        insert plan;
        
        PlanTravelHours.totalHours();
    }
    @isTest
    public static void testTotalHours1(){
        Plan__c plan=new Plan__c();
        plan.Travel_Hours__c=50;
        insert plan;
        
        PlanTravelHours.totalHours();
    }
    @isTest
    public static void stopCreatingPlansTest(){
        Try{
            Plan__c plan=new Plan__c();
        plan.Travel_Hours__c=50;
        plan.Travel_Location__c='A';
        insert plan;
        
        Plan__c plan1=new Plan__c();
        plan1.Travel_Hours__c=50;
        plan1.Travel_Location__c='B';
        insert plan1;
        
        Plan__c plan2=new Plan__c();
        plan2.Travel_Hours__c=50;
        plan2.Travel_Location__c='A';
        insert plan2;
        
        Plan__c plan3=new Plan__c();
        plan3.Travel_Hours__c=50;
        plan3.Travel_Location__c='A';
        insert plan3;
        }
        Catch(Exception e){
            System.debug('Error Occured');
        }        
    }
}