main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Plan__c/fields/Travel_Hours__c.field-meta.xml
<CustomField>
    <fullName>Travel_Hours__c</fullName>
    <label>Travel Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Plan__c/fields/Travel_Location__c.field-meta.xml
<CustomField>
    <fullName>Travel_Location__c</fullName>
    <label>Travel Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/PlanTravelHours.cls
//Write a script to get the total hours of all the Plans
//record having Multipicklist A or F selected only or with other values."
// Plan__c  Travel_Hours__c Travel_Location__c

public class PlanTravelHours {
    
    public static void totalHours(){
        
        Map<ID,Plan__c> plans=new Map<ID,Plan__c>([select Travel_Hours__c,Travel_Location__c from Plan__c limit 4500]);
        System.debug('Plans recieved '+plans);
        
        try{
            Decimal hours=0;
            
            for(Plan__c plan:plans.values())
            {
                
                System.debug('Plan '+plan);
                System.debug('Travel Location '+plan.Travel_Location__c);
                if(plan.Travel_Location__c==NULL){
                    plan.Travel_Location__c='';
                }
                if(plan.Travel_Location__c.contains('A') || plan.Travel_Location__c.contains('F'))
                {
                    System.debug(' Travel hours >>>>>> '+plan.Travel_Hours__c);
                    hours +=plan.Travel_Hours__c;
                }
            }
            System.debug('total hours of all the Plans :: '+hours);
        }
        Catch(Exception e){
            System.debug('Exception caught '+e.getLineNumber());
            System.debug(e.getMessage());
        }
        
        
        
        
        
    }
}