main/default/objects/Login_Users__c/Login_Users__c.object-meta.xml
<CustomObject>
    <label>Login Users</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Login_Users__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Login_Users__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Contact Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Login_Users__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>25</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

main/default/objects/Login_Users__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/classes/forgetPasswordApexController.cls
public class forgetPasswordApexController {
    
    @AuraEnabled
    public static Boolean matchAnswer(String answer,String username, String email){
        List<Login_Users__c> user=[select id,Password__c,Name,Username__c,Answer__c from Login_Users__c where Username__c =:username OR Contact_email__c =:email limit 1];
        if(!user.isEmpty()){
            if(user[0].Answer__c==answer){
                return true;
            }else
            {
                return false;
            }
            
        }
        else
        {
            return false;
        }
        
    }
    
    @AuraEnabled
    public static String findAccount(String username, String email){
        List<Login_Users__c> user=[select id,Password__c,Name,Username__c from Login_Users__c where Username__c =:username OR Contact_email__c =:email limit 1];
        
        if(!user.isEmpty()){
            return user[0].Username__c;
        }
        else
        {
            return 'Sorry! NO User Found';
        }
        
    }
    
    @AuraEnabled
    public static Boolean resetPassword(String username, String newPassword){
        List<Login_Users__c> user=[select id,Password__c,Name from Login_Users__c where Username__c =:username limit 1];
        
        if(!user.isEmpty()){
           // if(user[0].Password__c==oldPassword)
            {
                user[0].Password__c=newPassword;
                
                update user;
                return true;
            }
           /* else{
                return false;
            } */
        }
        else
        {
            return false;
        }
        
    }    
    
}