main/default/objects/Login_Users__c/Login_Users__c.object-meta.xml
<CustomObject>
    <label>Login Users</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Login_Users__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>25</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

main/default/objects/Login_Users__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/classes/LoginControllerApex.cls
public class LoginControllerApex {
    @AuraEnabled
    public static Boolean getDetails(String username, String password){
        
        if(username==NULL)
            //return 'Please Enter a UserName';
        return false;
        
      List<Login_Users__c> LoginList=[Select Id,Username__c,Password__c from Login_Users__c where Username__c =: username Limit 1];
            
        
        
        if(LoginList.isEmpty())
        {
            //return 'No Username found'; 
            return false;
        }
        else
        {
            if(LoginList[0].Password__c.equals(password))
            {
                //return 'Welcome! Logged in.';
                return true;
            }
            else
            {
                //return 'Oops sorry! Wrong password';
                return false;
            }
            
        }
    }
}